baseURL = "https://examplesite.com"
googleAnalytics = ""
theme = "RxSoft "
title = "RxSoft Knowledge as a service"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "mission"
name = "About"
pre = "#"
weight = 1
[[menu.main]]
URL = "products"
name = "Products"
pre = "#"
weight = 2
[[menu.main]]
URL = "career"
name = "Career"
pre = ""
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
pre = "#"
weight = 4
[params]
author = "c"
contact_info = ""
description = "c"
logo = "images/logo_size_invert.jpg"
logo_width = "120px"
preloader = true
social = []
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw"
map_center_lat = "25.773606"
map_center_lng = "-80.732655"
map_marker = "images/map-marker.png"
map_position_lat = "25.7635916"
map_position_lng = "-80.1937595"
